/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estruturas;

import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Nicolas
 */
public class ElevadorMain extends javax.swing.JFrame {

    private Elevador elevador = new Elevador(12);

    /**
     * Creates new form ElevadorMain
     */
    public ElevadorMain() {
        initComponents();
        lblAndarAtual.setText("T");
        lblDirection.setText("▲");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLeft = new javax.swing.JPanel();
        PanelTerreo = new javax.swing.JPanel();
        LabelTerreo = new javax.swing.JLabel();
        BtnTerreo = new javax.swing.JButton();
        Panel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Btn1 = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        Label2 = new javax.swing.JLabel();
        Btn2 = new javax.swing.JButton();
        Panel3 = new javax.swing.JPanel();
        Label3 = new javax.swing.JLabel();
        Btn3 = new javax.swing.JButton();
        Panel4 = new javax.swing.JPanel();
        Label4 = new javax.swing.JLabel();
        Btn4 = new javax.swing.JButton();
        Panel5 = new javax.swing.JPanel();
        Label5 = new javax.swing.JLabel();
        Btn5 = new javax.swing.JButton();
        PanelValue = new javax.swing.JPanel();
        lblAndarAtual = new javax.swing.JLabel();
        lblDirection = new javax.swing.JLabel();
        PanelRight = new javax.swing.JPanel();
        Panel6 = new javax.swing.JPanel();
        Label6 = new javax.swing.JLabel();
        Btn6 = new javax.swing.JButton();
        Panel7 = new javax.swing.JPanel();
        Label7 = new javax.swing.JLabel();
        Btn7 = new javax.swing.JButton();
        Panel8 = new javax.swing.JPanel();
        Label8 = new javax.swing.JLabel();
        Btn8 = new javax.swing.JButton();
        Panel9 = new javax.swing.JPanel();
        Label9 = new javax.swing.JLabel();
        Btn9 = new javax.swing.JButton();
        Panel10 = new javax.swing.JPanel();
        Label10 = new javax.swing.JLabel();
        Btn10 = new javax.swing.JButton();
        Panel11 = new javax.swing.JPanel();
        Label11 = new javax.swing.JLabel();
        Btn11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elevador");
        setBackground(new java.awt.Color(204, 204, 204));
        setBounds(new java.awt.Rectangle(0, 0, 200, 200));
        setResizable(false);

        PanelLeft.setBackground(new java.awt.Color(204, 204, 204));

        PanelTerreo.setBackground(new java.awt.Color(255, 255, 255));

        LabelTerreo.setBackground(new java.awt.Color(255, 255, 255));
        LabelTerreo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelTerreo.setText("T");

        BtnTerreo.setBackground(new java.awt.Color(255, 255, 255));
        BtnTerreo.setFocusPainted(false);
        BtnTerreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnTerreoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PanelTerreoLayout = new javax.swing.GroupLayout(PanelTerreo);
        PanelTerreo.setLayout(PanelTerreoLayout);
        PanelTerreoLayout.setHorizontalGroup(
            PanelTerreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTerreoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTerreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(BtnTerreo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelTerreoLayout.setVerticalGroup(
            PanelTerreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTerreoLayout.createSequentialGroup()
                .addGroup(PanelTerreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTerreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelTerreoLayout.createSequentialGroup()
                        .addComponent(BtnTerreo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        LabelTerreo.getAccessibleContext().setAccessibleName("");

        Panel1.setBackground(new java.awt.Color(255, 255, 255));

        Label1.setBackground(new java.awt.Color(255, 255, 255));
        Label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label1.setText("1");

        Btn1.setBackground(new java.awt.Color(255, 255, 255));
        Btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Panel2.setBackground(new java.awt.Color(255, 255, 255));

        Label2.setBackground(new java.awt.Color(255, 255, 255));
        Label2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label2.setText("2");

        Btn2.setBackground(new java.awt.Color(255, 255, 255));
        Btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Panel3.setBackground(new java.awt.Color(255, 255, 255));

        Label3.setBackground(new java.awt.Color(255, 255, 255));
        Label3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label3.setText("3");

        Btn3.setBackground(new java.awt.Color(255, 255, 255));
        Btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Panel4.setBackground(new java.awt.Color(255, 255, 255));

        Label4.setBackground(new java.awt.Color(255, 255, 255));
        Label4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label4.setText("4");

        Btn4.setBackground(new java.awt.Color(255, 255, 255));
        Btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel4Layout = new javax.swing.GroupLayout(Panel4);
        Panel4.setLayout(Panel4Layout);
        Panel4Layout.setHorizontalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel4Layout.setVerticalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel4Layout.createSequentialGroup()
                        .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Panel5.setBackground(new java.awt.Color(255, 255, 255));

        Label5.setBackground(new java.awt.Color(255, 255, 255));
        Label5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label5.setText("5");

        Btn5.setBackground(new java.awt.Color(255, 255, 255));
        Btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel5Layout = new javax.swing.GroupLayout(Panel5);
        Panel5.setLayout(Panel5Layout);
        Panel5Layout.setHorizontalGroup(
            Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel5Layout.setVerticalGroup(
            Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel5Layout.createSequentialGroup()
                .addGroup(Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel5Layout.createSequentialGroup()
                        .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelLeftLayout = new javax.swing.GroupLayout(PanelLeft);
        PanelLeft.setLayout(PanelLeftLayout);
        PanelLeftLayout.setHorizontalGroup(
            PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTerreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelLeftLayout.setVerticalGroup(
            PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTerreo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelValue.setBackground(new java.awt.Color(0, 0, 0));
        PanelValue.setForeground(new java.awt.Color(255, 0, 0));
        PanelValue.setAlignmentX(1.0F);

        lblAndarAtual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAndarAtual.setForeground(new java.awt.Color(153, 0, 0));
        lblAndarAtual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAndarAtual.setText("0");
        lblAndarAtual.setName("lblAndarAtual"); // NOI18N

        lblDirection.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDirection.setForeground(new java.awt.Color(153, 0, 0));
        lblDirection.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDirection.setText("▲");
        lblDirection.setName("lblDirection"); // NOI18N

        javax.swing.GroupLayout PanelValueLayout = new javax.swing.GroupLayout(PanelValue);
        PanelValue.setLayout(PanelValueLayout);
        PanelValueLayout.setHorizontalGroup(
            PanelValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelValueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAndarAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDirection)
                .addGap(90, 90, 90))
        );
        PanelValueLayout.setVerticalGroup(
            PanelValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelValueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAndarAtual)
                    .addComponent(lblDirection))
                .addContainerGap())
        );

        lblDirection.getAccessibleContext().setAccessibleParent(lblDirection);

        PanelRight.setBackground(new java.awt.Color(204, 204, 204));

        Panel6.setBackground(new java.awt.Color(255, 255, 255));

        Label6.setBackground(new java.awt.Color(255, 255, 255));
        Label6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label6.setText("6");

        Btn6.setBackground(new java.awt.Color(255, 255, 255));
        Btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel6Layout = new javax.swing.GroupLayout(Panel6);
        Panel6.setLayout(Panel6Layout);
        Panel6Layout.setHorizontalGroup(
            Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel6Layout.setVerticalGroup(
            Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel6Layout.createSequentialGroup()
                .addGroup(Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel6Layout.createSequentialGroup()
                        .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Panel7.setBackground(new java.awt.Color(255, 255, 255));

        Label7.setBackground(new java.awt.Color(255, 255, 255));
        Label7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label7.setText("7");

        Btn7.setBackground(new java.awt.Color(255, 255, 255));
        Btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel7Layout = new javax.swing.GroupLayout(Panel7);
        Panel7.setLayout(Panel7Layout);
        Panel7Layout.setHorizontalGroup(
            Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel7Layout.setVerticalGroup(
            Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel7Layout.createSequentialGroup()
                .addGroup(Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel7Layout.createSequentialGroup()
                        .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Panel8.setBackground(new java.awt.Color(255, 255, 255));

        Label8.setBackground(new java.awt.Color(255, 255, 255));
        Label8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label8.setText("8");

        Btn8.setBackground(new java.awt.Color(255, 255, 255));
        Btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel8Layout = new javax.swing.GroupLayout(Panel8);
        Panel8.setLayout(Panel8Layout);
        Panel8Layout.setHorizontalGroup(
            Panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel8Layout.setVerticalGroup(
            Panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel8Layout.createSequentialGroup()
                .addGroup(Panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel8Layout.createSequentialGroup()
                        .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Panel9.setBackground(new java.awt.Color(255, 255, 255));

        Label9.setBackground(new java.awt.Color(255, 255, 255));
        Label9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label9.setText("9");

        Btn9.setBackground(new java.awt.Color(255, 255, 255));
        Btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn9MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel9Layout = new javax.swing.GroupLayout(Panel9);
        Panel9.setLayout(Panel9Layout);
        Panel9Layout.setHorizontalGroup(
            Panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel9Layout.setVerticalGroup(
            Panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel9Layout.createSequentialGroup()
                .addGroup(Panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel9Layout.createSequentialGroup()
                        .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Panel10.setBackground(new java.awt.Color(255, 255, 255));

        Label10.setBackground(new java.awt.Color(255, 255, 255));
        Label10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label10.setText("10");

        Btn10.setBackground(new java.awt.Color(255, 255, 255));
        Btn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn10MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel10Layout = new javax.swing.GroupLayout(Panel10);
        Panel10.setLayout(Panel10Layout);
        Panel10Layout.setHorizontalGroup(
            Panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(Btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel10Layout.setVerticalGroup(
            Panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel10Layout.createSequentialGroup()
                .addGroup(Panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel10Layout.createSequentialGroup()
                        .addComponent(Btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Panel11.setBackground(new java.awt.Color(255, 255, 255));

        Label11.setBackground(new java.awt.Color(255, 255, 255));
        Label11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label11.setText("11");

        Btn11.setBackground(new java.awt.Color(255, 255, 255));
        Btn11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn11MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel11Layout = new javax.swing.GroupLayout(Panel11);
        Panel11.setLayout(Panel11Layout);
        Panel11Layout.setHorizontalGroup(
            Panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(Btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel11Layout.setVerticalGroup(
            Panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel11Layout.createSequentialGroup()
                .addGroup(Panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel11Layout.createSequentialGroup()
                        .addComponent(Btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelRightLayout = new javax.swing.GroupLayout(PanelRight);
        PanelRight.setLayout(PanelRightLayout);
        PanelRightLayout.setHorizontalGroup(
            PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Panel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelRightLayout.setVerticalGroup(
            PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(PanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(PanelValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void escutaMovimento() {
        Timer timer = new Timer();
        if (elevador.emMovimento()) {
            timer.scheduleAtFixedRate(new TimerTask() {
                @Override
                public void run() {
                    if (elevador.getDirecao().equalsIgnoreCase("up")) {
                        lblDirection.setText("▲");
                    } else {
                        lblDirection.setText("▼");
                    }
                    System.out.println("Andar Interface: "+ elevador.getAndarAtual());
                    switch (elevador.getAndarAtual()) {
                        case 0:
                            lblAndarAtual.setText("T");
                            BtnTerreo.setBackground(Color.white);
                            break;
                        case 1:
                            lblAndarAtual.setText("" + elevador.getAndarAtual());
                            Btn1.setBackground(Color.white);
                            break;
                        case 2:
                            lblAndarAtual.setText("" + elevador.getAndarAtual());
                            Btn2.setBackground(Color.white);
                            break;
                        case 3:
                            lblAndarAtual.setText("" + elevador.getAndarAtual());
                            Btn3.setBackground(Color.white);
                            break;
                        case 4:
                            lblAndarAtual.setText("" + elevador.getAndarAtual());
                            Btn4.setBackground(Color.white);
                            break;
                        case 5:
                            lblAndarAtual.setText("" + elevador.getAndarAtual());
                            Btn5.setBackground(Color.white);
                            break;
                        case 6:
                            lblAndarAtual.setText("" + elevador.getAndarAtual());
                            Btn6.setBackground(Color.white);
                            break;
                        case 7:
                            lblAndarAtual.setText("" + elevador.getAndarAtual());
                            Btn7.setBackground(Color.white);
                            break;
                        case 8:
                            lblAndarAtual.setText("" + elevador.getAndarAtual());
                            Btn8.setBackground(Color.white);
                            break;
                        case 9:
                            lblAndarAtual.setText("" + elevador.getAndarAtual());
                            Btn9.setBackground(Color.white);
                            break;
                        case 10:
                            lblAndarAtual.setText("" + elevador.getAndarAtual());
                            Btn10.setBackground(Color.white);
                            break;
                        case 11:
                            lblAndarAtual.setText("" + elevador.getAndarAtual());
                            Btn11.setBackground(Color.white);
                            break;
                    }
                    if (!elevador.emMovimento()) {
                        timer.cancel();
                    }
                }
            }, 1000, 1000);
        } else {
            timer.cancel();
        }
    }

    private void BtnTerreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTerreoMousePressed
        if (!elevador.isPushed(0) && elevador.getAndarAtual() != 0) {
            BtnTerreo.setBackground(Color.red);
            elevador.chamar(0);
            escutaMovimento();
        }
    }//GEN-LAST:event_BtnTerreoMousePressed

    private void Btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MousePressed
        if (!elevador.isPushed(1)) {
            Btn1.setBackground(Color.red);
            elevador.chamar(1);
            escutaMovimento();
        }
    }//GEN-LAST:event_Btn1MousePressed

    private void Btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2MousePressed
        if (!elevador.isPushed(2)) {
            Btn2.setBackground(Color.red);
            elevador.chamar(2);
            escutaMovimento();
        }
    }//GEN-LAST:event_Btn2MousePressed

    private void Btn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3MousePressed
        if (!elevador.isPushed(3)) {
            Btn3.setBackground(Color.red);
            elevador.chamar(3);
            escutaMovimento();
        }
    }//GEN-LAST:event_Btn3MousePressed

    private void Btn4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn4MousePressed
        if (!elevador.isPushed(4)) {
            Btn4.setBackground(Color.red);
            elevador.chamar(4);
            escutaMovimento();
        }
    }//GEN-LAST:event_Btn4MousePressed

    private void Btn5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn5MousePressed
        if (!elevador.isPushed(5)) {
            Btn5.setBackground(Color.red);
            elevador.chamar(5);
            escutaMovimento();
        }
    }//GEN-LAST:event_Btn5MousePressed

    private void Btn6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn6MousePressed
        if (!elevador.isPushed(6)) {
            Btn6.setBackground(Color.red);
            elevador.chamar(6);
            escutaMovimento();
        }
    }//GEN-LAST:event_Btn6MousePressed

    private void Btn7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn7MousePressed
        if (!elevador.isPushed(7)) {
            Btn7.setBackground(Color.red);
            elevador.chamar(7);
            escutaMovimento();
        }
    }//GEN-LAST:event_Btn7MousePressed

    private void Btn8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn8MousePressed
        if (!elevador.isPushed(8)) {
            Btn8.setBackground(Color.red);
            elevador.chamar(8);
            escutaMovimento();
        }
    }//GEN-LAST:event_Btn8MousePressed

    private void Btn9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn9MousePressed
        if (!elevador.isPushed(9)) {
            Btn9.setBackground(Color.red);
            elevador.chamar(9);
            escutaMovimento();
        }
    }//GEN-LAST:event_Btn9MousePressed

    private void Btn10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn10MousePressed
        if (!elevador.isPushed(10)) {
            Btn10.setBackground(Color.red);
            elevador.chamar(10);
            escutaMovimento();
        }
    }//GEN-LAST:event_Btn10MousePressed

    private void Btn11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn11MousePressed
        if (!elevador.isPushed(11)) {
            Btn11.setBackground(Color.red);
            elevador.chamar(11);
            escutaMovimento();
        }
    }//GEN-LAST:event_Btn11MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElevadorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElevadorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElevadorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElevadorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElevadorMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn10;
    private javax.swing.JButton Btn11;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnTerreo;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label11;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel Label9;
    private javax.swing.JLabel LabelTerreo;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel10;
    private javax.swing.JPanel Panel11;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JPanel Panel5;
    private javax.swing.JPanel Panel6;
    private javax.swing.JPanel Panel7;
    private javax.swing.JPanel Panel8;
    private javax.swing.JPanel Panel9;
    private javax.swing.JPanel PanelLeft;
    private javax.swing.JPanel PanelRight;
    private javax.swing.JPanel PanelTerreo;
    private javax.swing.JPanel PanelValue;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JLabel lblAndarAtual;
    private javax.swing.JLabel lblDirection;
    // End of variables declaration//GEN-END:variables
}
